version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
      - dependency-type: "all"
    commit-message:
      prefix: "deps(npm)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:30"
      timezone: "UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(actions)"