version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: invorto
      POSTGRES_PASSWORD: invorto
      POSTGRES_DB: invorto
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  telephony:
    build: ./services/telephony
    environment:
      - REALTIME_WS_URL=http://localhost:8081/v1/realtime
      - PUBLIC_BASE_URL=http://localhost:8085
    ports:
      - "8085:8085"
    depends_on:
      - redis

