name: Terraform Validate

on:
  # ⚠️  DISABLED: Skip terraform validation to prevent infrastructure changes
  workflow_dispatch: # Only run manually if needed

jobs:
  validate:
    runs-on: ubuntu-latest
    # ⚠️  DISABLED: Skip terraform validation
    if: false # Disabled to prevent accidental infrastructure changes
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform fmt
        working-directory: infra/terraform
        run: terraform fmt -recursive -check

      - name: Terraform init (no backend)
        working-directory: infra/terraform
        run: terraform init -backend=false

      - name: Terraform validate
        working-directory: infra/terraform
        run: terraform validate